// Code generated by protoc-gen-go.
// source: example.proto
// DO NOT EDIT!
package protobuf

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Example struct {
	Label *string `protobuf:"bytes,1,req,name=label" json:"label,omitempty"`
}

func (m *Example) Reset()         { *m = Example{} }
func (m *Example) String() string { return proto.CompactTextString(m) }
func (*Example) ProtoMessage()    {}

func (m *Example) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}
